/*
Set the environment variables for the Vite app and local scripts
Pulls values from .env.config.js and does two things:
- Generates a .env file for local development
- Updates the VITE_CONFIG GitHub secret for production usage
*/

// Note: This script assumes you have the `gh` CLI installed and authenticated

import fs from 'fs';
import { execSync } from 'child_process';
import { viteConfig, localScriptConfig } from './.env.config.js';

if (!viteConfig || !localScriptConfig) {
  throw new Error('Invalid configuration: .env.json viteConfig and localScriptConfig are required');
}

const generateEnv = () => {

// Don't indent this string
const envContent = `# This file is generated by generate-env.js
# Do not edit manually!

VITE_CONFIG=${JSON.stringify(viteConfig)}

# Only used by local npm scripts
SCRIPTS_TEST_DOMAINS="${localScriptConfig.SCRIPTS_TEST_DOMAINS}"
CLOUD_FUNCTIONS_TRIGGER_TOKEN="${localScriptConfig.CLOUD_FUNCTIONS_TRIGGER_TOKEN}"`;

  fs.writeFileSync('.env', envContent);
  console.log('✅ Generated .env file');
}

const updateGithubSecret = async () => {
  try {
    const viteConfigJson = JSON.stringify(viteConfig)
    execSync(`gh secret set VITE_CONFIG --body '${viteConfigJson}'`, { stdio: 'inherit' });
    console.log('✅ Updated VITE_CONFIG GitHub secret');
  }
  catch (error) {
    console.error('❌ Error updating GitHub secret:', error);
  }
}

generateEnv();
await updateGithubSecret();
