name: Deploy to Firebase Hosting manually
'on':
  workflow_dispatch:

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    env:
      VITE_SANDBOX_MODE: ${{ secrets.VITE_SANDBOX_MODE }}
      VITE_WAITLIST_MODE: ${{ secrets.VITE_WAITLIST_MODE }}
      VITE_SKIP_MANDATORY_FIELDS: ${{ secrets.VITE_SKIP_MANDATORY_FIELDS }}
      VITE_STRIPE_PUBLISHABLE_KEY_SANDBOX: ${{ secrets.VITE_STRIPE_PUBLISHABLE_KEY_SANDBOX }}
      VITE_STRIPE_PUBLISHABLE_KEY_LIVE: ${{ secrets.VITE_STRIPE_PUBLISHABLE_KEY_LIVE }}
      VITE_PAYPAL_CLIENT_ID_SANDBOX: ${{ secrets.VITE_PAYPAL_CLIENT_ID_SANDBOX }}
      VITE_PAYPAL_CLIENT_ID_LIVE: ${{ secrets.VITE_PAYPAL_CLIENT_ID_LIVE }}
      VITE_RECAPTCHA_SITE_KEY: ${{ secrets.VITE_RECAPTCHA_SITE_KEY }}
      VITE_GOOGLE_PLACES_API_KEY: ${{ secrets.VITE_GOOGLE_PLACES_API_KEY }}
      VITE_FIREBASE_API_KEY: ${{ secrets.VITE_FIREBASE_API_KEY }}
      VITE_FIREBASE_AUTH_DOMAIN: ${{ secrets.VITE_FIREBASE_AUTH_DOMAIN }}
      VITE_FIREBASE_PROJECT_ID: ${{ secrets.VITE_FIREBASE_PROJECT_ID }}
      VITE_FIREBASE_STORAGE_BUCKET: ${{ secrets.VITE_FIREBASE_STORAGE_BUCKET }}
      VITE_FIREBASE_MESSAGING_SENDER_ID: ${{ secrets.VITE_FIREBASE_MESSAGING_SENDER_ID }}
      VITE_FIREBASE_APP_ID: ${{ secrets.VITE_FIREBASE_APP_ID }}
      VITE_FIREBASE_DATABASE_URL: ${{ secrets.VITE_FIREBASE_DATABASE_URL }}
    steps:
      - uses: actions/checkout@v3
      - name: npm install
        run: npm install
      - name: build
        run: npm run build
      - uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: '${{ secrets.GITHUB_TOKEN }}'
          firebaseServiceAccount: '${{ secrets.FIREBASE_SERVICE_ACCOUNT_CONTRA_TESTING }}'
          channelId: live
          projectId: '${{ secrets.VITE_FIREBASE_PROJECT_ID }}'
