name: Deploy to Firebase Hosting
on:
  push:
    branches:
      - main
      - staging
  workflow_dispatch:

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    env:
      DOPPLER_TOKEN: ${{ github.ref_name == 'main' && secrets.DOPPLER_TOKEN_PRD || secrets.DOPPLER_TOKEN_STG }}
      DOPPLER_STAGE: ${{ (github.ref_name == 'main' && 'prd') || 'stg' }}
      FIREBASE_CHANNEL: ${{ (github.ref_name == 'main' && 'live') || 'staging' }}
      IS_PRODUCTION: ${{ github.ref_name == 'main' }}
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Install Dependencies
        run: npm install

      - name: Fetch Secrets from Doppler
        uses: dopplerhq/secrets-fetch-action@v1.3.0
        id: doppler
        with:
          doppler-token: ${{ env.DOPPLER_TOKEN }}
          inject-env-vars: true

      - name: Build Project
        run: npm run build

      - name: Deploy to Firebase Hosting
        uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: '${{ secrets.GITHUB_TOKEN }}'
          channelId: ${{ env.FIREBASE_CHANNEL }}
          projectId: 'contra-testing'
          firebaseServiceAccount: '${{ secrets.FIREBASE_SERVICE_ACCOUNT_CONTRA_TESTING }}'
